// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDxJPvLa5Eh_ABfMJ2vQWwJSOqDLHpCI',
    appId: '1:882938165675:web:07f83b4c894570af88faee',
    messagingSenderId: '882938165675',
    projectId: 'garagesynch',
    authDomain: 'garagesynch.firebaseapp.com',
    storageBucket: 'garagesynch.firebasestorage.app',
    measurementId: 'G-YE1J4PC1R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz44MI_EbZxLIBX1AEiW-lhm1J3E0C33E',
    appId: '1:882938165675:android:096392d8c198549a88faee',
    messagingSenderId: '882938165675',
    projectId: 'garagesynch',
    storageBucket: 'garagesynch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9WUXgClGPdi_l1nT_amNtMlEu5cJvYB0',
    appId: '1:882938165675:ios:8b79741ef5a9fc2088faee',
    messagingSenderId: '882938165675',
    projectId: 'garagesynch',
    storageBucket: 'garagesynch.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9WUXgClGPdi_l1nT_amNtMlEu5cJvYB0',
    appId: '1:882938165675:ios:8b79741ef5a9fc2088faee',
    messagingSenderId: '882938165675',
    projectId: 'garagesynch',
    storageBucket: 'garagesynch.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjDxJPvLa5Eh_ABfMJ2vQWwJSOqDLHpCI',
    appId: '1:882938165675:web:eae23c9f458b8af788faee',
    messagingSenderId: '882938165675',
    projectId: 'garagesynch',
    authDomain: 'garagesynch.firebaseapp.com',
    storageBucket: 'garagesynch.firebasestorage.app',
    measurementId: 'G-309YNHHN4W',
  );

}